// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wms.Infrastructure.Persistence;

#nullable disable

namespace Wms.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WmsDbContext))]
    [Migration("20260927073138_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wms.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("NewValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasColumnType("jsonb")
                        .HasColumnName("old_value");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_no");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_type");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Username")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_audit_logs");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_audit_logs_created_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.HasIndex("Module", "Action")
                        .HasDatabaseName("ix_audit_logs_module_action");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.InboundDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InboundOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbound_order_id");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<decimal>("OrderedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("ordered_quantity");

                    b.Property<decimal>("PutawayQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("putaway_quantity");

                    b.Property<decimal>("ReceivedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("received_quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_inbound_details");

                    b.HasIndex("InboundOrderId")
                        .HasDatabaseName("ix_inbound_details_inbound_order_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_inbound_details_material_id");

                    b.ToTable("inbound_details", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.InboundOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExpectedArrivalDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expected_arrival_date");

                    b.Property<string>("ExternalOrderNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_order_no");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_no");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("SupplierCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("supplier_code");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("supplier_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inbound_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_inbound_orders_created_at");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_inbound_orders_order_no");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_inbound_orders_warehouse_id_status");

                    b.ToTable("inbound_orders", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AvailableQuantity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("available_quantity")
                        .HasComputedColumnSql("quantity - reserved_quantity", true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("ReservedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("reserved_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_inventories_material_id");

                    b.HasIndex("WarehouseId", "MaterialId")
                        .HasDatabaseName("ix_inventories_warehouse_id_material_id");

                    b.HasIndex("LocationId", "MaterialId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ix_inventories_location_id_material_id_status");

                    b.ToTable("inventories", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventories_quantity_non_negative", "quantity >= 0");

                            t.HasCheckConstraint("ck_inventories_reserved_le_quantity", "reserved_quantity <= quantity");

                            t.HasCheckConstraint("ck_inventories_reserved_non_negative", "reserved_quantity >= 0");
                        });
                });

            modelBuilder.Entity("Wms.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BalanceAfter")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("balance_after");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid?>("OperatorId")
                        .HasColumnType("uuid")
                        .HasColumnName("operator_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("ReferenceNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("reference_no");

                    b.Property<string>("ReferenceType")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("reference_type");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<Guid?>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.Property<string>("TransactionNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transaction_no");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("transaction_type");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_inventory_transactions");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_inventory_transactions_created_at");

                    b.HasIndex("FromLocationId")
                        .HasDatabaseName("ix_inventory_transactions_from_location_id");

                    b.HasIndex("ToLocationId")
                        .HasDatabaseName("ix_inventory_transactions_to_location_id");

                    b.HasIndex("TransactionNo")
                        .IsUnique()
                        .HasDatabaseName("ix_inventory_transactions_transaction_no");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_inventory_transactions_warehouse_id");

                    b.HasIndex("MaterialId", "CreatedAt")
                        .HasDatabaseName("ix_inventory_transactions_material_id_created_at");

                    b.HasIndex("ReferenceType", "ReferenceId")
                        .HasDatabaseName("ix_inventory_transactions_reference_type_reference_id");

                    b.ToTable("inventory_transactions", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Capacity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("capacity");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("location_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<decimal>("WeightLimit")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("weight_limit");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_code");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_locations_zone_id");

                    b.HasIndex("WarehouseId", "ZoneId")
                        .HasDatabaseName("ix_locations_warehouse_id_zone_id");

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseUom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("base_uom");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal>("MaxStock")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("max_stock");

                    b.Property<decimal>("MinStock")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("min_stock");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("SafetyStock")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("safety_stock");

                    b.Property<string>("Specification")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("specification");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_materials");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_materials_category_id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_materials_code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_materials_is_active");

                    b.ToTable("materials", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.MaterialBarcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("barcode");

                    b.Property<string>("BarcodeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("barcode_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.HasKey("Id")
                        .HasName("pk_material_barcodes");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_material_barcodes_barcode");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_material_barcodes_material_id");

                    b.ToTable("material_barcodes", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.MaterialCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_material_categories");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_material_categories_code");

                    b.ToTable("material_categories", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.NumberSequence", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<long>("CurrentValue")
                        .HasColumnType("bigint")
                        .HasColumnName("current_value");

                    b.HasKey("Key")
                        .HasName("pk_number_sequences");

                    b.ToTable("number_sequences", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.OutboundDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AllocatedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("allocated_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("LineNo")
                        .HasColumnType("integer")
                        .HasColumnName("line_no");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("OutboundOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_order_id");

                    b.Property<decimal>("PickedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("picked_quantity");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<decimal>("RequestedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("requested_quantity");

                    b.Property<decimal>("ShippedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("shipped_quantity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_outbound_details");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_outbound_details_material_id");

                    b.HasIndex("OutboundOrderId")
                        .HasDatabaseName("ix_outbound_details_outbound_order_id");

                    b.ToTable("outbound_details", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.OutboundOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("customer_code");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("customer_name");

                    b.Property<string>("ExternalOrderNo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("external_order_no");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("order_no");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<DateTime?>("RequestedShipDate")
                        .HasColumnType("timestamptz")
                        .HasColumnName("requested_ship_date");

                    b.Property<DateTime?>("ShippedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("shipped_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_outbound_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_outbound_orders_created_at");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("ix_outbound_orders_order_no");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_outbound_orders_warehouse_id_status");

                    b.ToTable("outbound_orders", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("action");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_code");

                    b.HasIndex("Module")
                        .HasDatabaseName("ix_permissions_module");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.PickTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<Guid>("OutboundDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("outbound_detail_id");

                    b.Property<decimal>("PickedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("picked_quantity");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("task_no");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_pick_tasks");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_pick_tasks_material_id");

                    b.HasIndex("OutboundDetailId")
                        .HasDatabaseName("ix_pick_tasks_outbound_detail_id");

                    b.HasIndex("SourceLocationId")
                        .HasDatabaseName("ix_pick_tasks_source_location_id");

                    b.HasIndex("TaskNo")
                        .IsUnique()
                        .HasDatabaseName("ix_pick_tasks_task_no");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_pick_tasks_warehouse_id_status");

                    b.ToTable("pick_tasks", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.PutawayTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InboundDetailId")
                        .HasColumnType("uuid")
                        .HasColumnName("inbound_detail_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<Guid?>("SourceLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_location_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid?>("TargetLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_location_id");

                    b.Property<string>("TaskNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("task_no");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_putaway_tasks");

                    b.HasIndex("InboundDetailId")
                        .HasDatabaseName("ix_putaway_tasks_inbound_detail_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_putaway_tasks_material_id");

                    b.HasIndex("SourceLocationId")
                        .HasDatabaseName("ix_putaway_tasks_source_location_id");

                    b.HasIndex("TargetLocationId")
                        .HasDatabaseName("ix_putaway_tasks_target_location_id");

                    b.HasIndex("TaskNo")
                        .IsUnique()
                        .HasDatabaseName("ix_putaway_tasks_task_no");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_putaway_tasks_warehouse_id_status");

                    b.ToTable("putaway_tasks", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_roles_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Stocktake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("StocktakeNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("stocktake_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<Guid?>("ZoneId")
                        .HasColumnType("uuid")
                        .HasColumnName("zone_id");

                    b.HasKey("Id")
                        .HasName("pk_stocktakes");

                    b.HasIndex("StocktakeNo")
                        .IsUnique()
                        .HasDatabaseName("ix_stocktakes_stocktake_no");

                    b.HasIndex("ZoneId")
                        .HasDatabaseName("ix_stocktakes_zone_id");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_stocktakes_warehouse_id_status");

                    b.ToTable("stocktakes", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.StocktakeDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CountedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("counted_at");

                    b.Property<Guid?>("CountedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("counted_by");

                    b.Property<decimal?>("CountedQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("counted_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DifferenceQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("difference_quantity");

                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("location_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("StocktakeId")
                        .HasColumnType("uuid")
                        .HasColumnName("stocktake_id");

                    b.Property<decimal>("SystemQuantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("system_quantity");

                    b.HasKey("Id")
                        .HasName("pk_stocktake_details");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_stocktake_details_location_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_stocktake_details_material_id");

                    b.HasIndex("StocktakeId")
                        .HasDatabaseName("ix_stocktake_details_stocktake_id");

                    b.HasIndex("StocktakeId", "LocationId", "MaterialId")
                        .IsUnique()
                        .HasDatabaseName("ix_stocktake_details_stocktake_id_location_id_material_id");

                    b.ToTable("stocktake_details", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.TransferOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("executed_at");

                    b.Property<Guid?>("ExecutedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("executed_by");

                    b.Property<Guid>("FromLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_location_id");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid")
                        .HasColumnName("material_id");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reason");

                    b.Property<string>("Remark")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("remark");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<Guid>("ToLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_location_id");

                    b.Property<string>("TransferNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("transfer_no");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_transfer_orders");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_transfer_orders_created_at");

                    b.HasIndex("FromLocationId")
                        .HasDatabaseName("ix_transfer_orders_from_location_id");

                    b.HasIndex("MaterialId")
                        .HasDatabaseName("ix_transfer_orders_material_id");

                    b.HasIndex("ToLocationId")
                        .HasDatabaseName("ix_transfer_orders_to_location_id");

                    b.HasIndex("TransferNo")
                        .IsUnique()
                        .HasDatabaseName("ix_transfer_orders_transfer_no");

                    b.HasIndex("WarehouseId", "Status")
                        .HasDatabaseName("ix_transfer_orders_warehouse_id_status");

                    b.ToTable("transfer_orders", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.UnitOfMeasure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_unit_of_measures");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_unit_of_measures_code");

                    b.ToTable("unit_of_measures", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("refresh_token_expires_at");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("RefreshToken")
                        .HasDatabaseName("ix_users_refresh_token");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouses_code");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.WarehouseZone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("zone_type");

                    b.HasKey("Id")
                        .HasName("pk_warehouse_zones");

                    b.HasIndex("WarehouseId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_warehouse_zones_warehouse_id_code");

                    b.ToTable("warehouse_zones", (string)null);
                });

            modelBuilder.Entity("Wms.Domain.Entities.InboundDetail", b =>
                {
                    b.HasOne("Wms.Domain.Entities.InboundOrder", "InboundOrder")
                        .WithMany("Details")
                        .HasForeignKey("InboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_inbound_details_inbound_orders_inbound_order_id");

                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inbound_details_materials_material_id");

                    b.Navigation("InboundOrder");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Wms.Domain.Entities.InboundOrder", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inbound_orders_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_locations_location_id");

                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventories_warehouses_warehouse_id");

                    b.Navigation("Location");

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_locations_from_location_id");

                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_inventory_transactions_locations_to_location_id");

                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_inventory_transactions_warehouses_warehouse_id");

                    b.Navigation("FromLocation");

                    b.Navigation("Material");

                    b.Navigation("ToLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Location", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_locations_warehouses_warehouse_id");

                    b.HasOne("Wms.Domain.Entities.WarehouseZone", "Zone")
                        .WithMany("Locations")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_locations_warehouse_zones_zone_id");

                    b.Navigation("Warehouse");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Material", b =>
                {
                    b.HasOne("Wms.Domain.Entities.MaterialCategory", "Category")
                        .WithMany("Materials")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_materials_material_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Wms.Domain.Entities.MaterialBarcode", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany("Barcodes")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_material_barcodes_materials_material_id");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("Wms.Domain.Entities.OutboundDetail", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbound_details_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.OutboundOrder", "OutboundOrder")
                        .WithMany("Details")
                        .HasForeignKey("OutboundOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_outbound_details_outbound_orders_outbound_order_id");

                    b.Navigation("Material");

                    b.Navigation("OutboundOrder");
                });

            modelBuilder.Entity("Wms.Domain.Entities.OutboundOrder", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_outbound_orders_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.Entities.PickTask", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pick_tasks_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.OutboundDetail", "OutboundDetail")
                        .WithMany("PickTasks")
                        .HasForeignKey("OutboundDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pick_tasks_outbound_details_outbound_detail_id");

                    b.HasOne("Wms.Domain.Entities.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pick_tasks_locations_source_location_id");

                    b.Navigation("Material");

                    b.Navigation("OutboundDetail");

                    b.Navigation("SourceLocation");
                });

            modelBuilder.Entity("Wms.Domain.Entities.PutawayTask", b =>
                {
                    b.HasOne("Wms.Domain.Entities.InboundDetail", "InboundDetail")
                        .WithMany("PutawayTasks")
                        .HasForeignKey("InboundDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_putaway_tasks_inbound_details_inbound_detail_id");

                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_putaway_tasks_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.Location", "SourceLocation")
                        .WithMany()
                        .HasForeignKey("SourceLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_putaway_tasks_locations_source_location_id");

                    b.HasOne("Wms.Domain.Entities.Location", "TargetLocation")
                        .WithMany()
                        .HasForeignKey("TargetLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_putaway_tasks_locations_target_location_id");

                    b.Navigation("InboundDetail");

                    b.Navigation("Material");

                    b.Navigation("SourceLocation");

                    b.Navigation("TargetLocation");
                });

            modelBuilder.Entity("Wms.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("Wms.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Stocktake", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stocktakes_warehouses_warehouse_id");

                    b.HasOne("Wms.Domain.Entities.WarehouseZone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_stocktakes_warehouse_zones_zone_id");

                    b.Navigation("Warehouse");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Wms.Domain.Entities.StocktakeDetail", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stocktake_details_locations_location_id");

                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stocktake_details_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.Stocktake", "Stocktake")
                        .WithMany("Details")
                        .HasForeignKey("StocktakeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stocktake_details_stocktakes_stocktake_id");

                    b.Navigation("Location");

                    b.Navigation("Material");

                    b.Navigation("Stocktake");
                });

            modelBuilder.Entity("Wms.Domain.Entities.TransferOrder", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Location", "FromLocation")
                        .WithMany()
                        .HasForeignKey("FromLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_orders_locations_from_location_id");

                    b.HasOne("Wms.Domain.Entities.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_orders_materials_material_id");

                    b.HasOne("Wms.Domain.Entities.Location", "ToLocation")
                        .WithMany()
                        .HasForeignKey("ToLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_orders_locations_to_location_id");

                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfer_orders_warehouses_warehouse_id");

                    b.Navigation("FromLocation");

                    b.Navigation("Material");

                    b.Navigation("ToLocation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("Wms.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Wms.Domain.Entities.WarehouseZone", b =>
                {
                    b.HasOne("Wms.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany("Zones")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_warehouse_zones_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Wms.Domain.Entities.InboundDetail", b =>
                {
                    b.Navigation("PutawayTasks");
                });

            modelBuilder.Entity("Wms.Domain.Entities.InboundOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Material", b =>
                {
                    b.Navigation("Barcodes");
                });

            modelBuilder.Entity("Wms.Domain.Entities.MaterialCategory", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("Wms.Domain.Entities.OutboundDetail", b =>
                {
                    b.Navigation("PickTasks");
                });

            modelBuilder.Entity("Wms.Domain.Entities.OutboundOrder", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Stocktake", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("Wms.Domain.Entities.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Wms.Domain.Entities.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Zones");
                });

            modelBuilder.Entity("Wms.Domain.Entities.WarehouseZone", b =>
                {
                    b.Navigation("Locations");
                });
#pragma warning restore 612, 618
        }
    }
}
